version: "3.9"

services:
  consumer-service:
    image: sarai961/consumer:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: sarai
      RABBITMQ_PASS: carrot
    ports:
      - "5001:5001"
    networks:
      - eda-net

networks:
  eda-net:
    external: true